#端口
server:
  port: 8000

#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    database:
      type: mysql
    url: jdbc:mysql://39.107.157.91:13306/dashu_frame?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: xxx666888

#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.kg.**.entity

#自定义配置
com:
  kg:
    swagger:
      title: "大树快速开发平台API"
      description: "基于swagger的Api接口信息"
      termsOfServiceUrl: "http://www.keepgrown.com"
      version: "1.0.0"
      concat:
        name: "ziro"
        www: "http://www.keepgrown.com"
        email: "877185959@qq.com"